version: '3'
services:
  nginx:
    image: hardcattle/nginx:1.0
    ports:
      - 80:80
    volumes:
      - /root/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /root/nginx/log:/var/log/nginx/
      - /root/nginx/html:/usr/share/nginx/html
    container_name: test
